# ----------------------------
# Makefile Options
# ----------------------------

NAME = Test
ICON = icon.png
DESCRIPTION = "Test"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
